# stable
newline_style = "unix"
hard_tabs = false
tab_spaces = 2
max_width = 120

# unstable
# just update the style guide when they are stable
# stability could be checked there https://rust-lang.github.io/rustfmt
#fn_single_line = true
#format_code_in_doc_comments = true
#overflow_delimited_expr = true
#reorder_impl_items = true
#struct_field_align_threshold = 20
#struct_lit_single_line = true
